model_list:
  - model_name: claude-opus-4-8
    litellm_params:
      model: "ollama_chat/laguna-xs-2.1:q8_0"
      api_key: "ollama"
      api_base: "http://192.168.80.1:11434"
      num_ctx: 32768
      num_thread: 8

  - model_name: claude-sonnet-4-6
    litellm_params:
      model: "ollama_chat/laguna-xs-2.1:q8_0"
      api_key: "ollama"
      api_base: "http://192.168.80.1:11434"
      num_ctx: 32768
      num_thread: 8

  - model_name: claude-haiku-4-5-20251001
    litellm_params:
      model: "ollama_chat/laguna-xs-2.1:q8_0"
      api_key: "ollama"
      api_base: "http://192.168.80.1:11434"
      num_ctx: 32768
      num_thread: 8
